/**
 * Created by giscafer on 2017/5/13.
 */

export const  PROJECTS: any = [
  {
    "type": ['all','vue','nodejs'],
    "img": "1",
    "title": "Ponitor",
    "subtitle": "Vue.js1.x • ES6 • Node.js • MongoDB",
    "meta": " [ P ] rice + M [ onitor ] = Ponitor 价格监测应用",
    "description": "天猫、淘宝、京东、Apple App的商品，监控商品价格发生变动时（每天定时器），推送消息（目前是发送邮件）， 商品价格趋势分析统计等！",
    "demoUrl": "http://project.xinong.wang:18080/",
    "gitUrl": "https://github.com/giscafer/Ponitor",
  },
  {
    "type": ['all','react'],
    "img": "2",
    "title": "react-ponitor",
    "subtitle": "react • react-redux",
    "meta": " [ P ] rice + M [ onitor ] = Ponitor 价格监测应用",
    "description": "天猫、淘宝、京东、Apple App的商品，监控商品价格发生变动时（每天定时器），推送消息（目前是发送邮件），商品价格趋势分析统计等！",
    "demoUrl": "http://giscafer.com/react-ponitor/",
    "gitUrl": "https://github.com/giscafer/react-ponitor",
  },{
    "type": ['all','other','java'],
    "img": "3",
    "title": "FinalScheduler",
    "subtitle": "JFinal2.0 • Bootstrap • SeaJS • FullCalender.js",
    "meta": "终极排班管理系统，灵活排班",
    "description": "终极排班管理系统，改变传统的排班模式！",
    "demoUrl": "",
    "gitUrl": "https://github.com/giscafer/FinalScheduler",
  },{
    "type": ['all','other','css'],
    "img": "4",
    "title": "hexo-theme-cafe",
    "subtitle": "HTML • CSS • Hexo",
    "meta": "自定义 Hexo 博客框架主题，追求简约、操作简单、阅读舒适度",
    "description": "A theme of Hexo that is aimed at pursuit of simplicity, simple operation, reading comfort. 追求简约、操作简单、阅读舒适度",
    "demoUrl": "http://cafe.giscafer.com",
    "gitUrl": "https://github.com/giscafer/hexo-theme-cafe",
  },{
    "type": ['all','other','wechat'],
    "img": "6",
    "title": "mapshaper-plus",
    "subtitle": "HTML • CSS • JavaScript",
    "meta": "Generate geojson files for Echarts Map,base on mapshaper",
    "description": "基于mapshaper对geojson地图数据的坐标信息进行压缩编码，并提供可直接生成压缩编码后的echarts map数据格式，" +
    "通过mapshaper-plus可以直接将shp格式数据转换为压缩后的echarts数据",
    "demoUrl": "http://giscafer.com/mapshaper-plus/",
    "gitUrl": "https://github.com/giscafer/mapshaper-plus",
  },{
    "type": ['all','other','wechat'],
    "img": "5",
    "title": "wechat-weapp-mapdemo",
    "subtitle": "HTML5 • CSS • JavaScript",
    "meta": "微信小程序开发demo，地图导航、marker标注",
    "description": "微信小程序开发demo，地图导航、marker标注",
    "demoUrl": "",
    "gitUrl": "https://github.com/giscafer/wechat-weapp-mapdemo",
  },{
    "type": ['all','angular','nodejs'],
    "img": "7",
    "title": "angular-chat",
    "subtitle": "Angular4 • Node.js • Socket.io",
    "meta": "（IM App）Chat App built using Angular and Socket.io",
    "description": "（IM App）Chat App built using Angular and Socket.io，模仿百度E秘聊天",
    "demoUrl": "http://project.xinong.wang:8080/",
    "gitUrl": "https://github.com/giscafer/angular-chat",
  },{
    "type": ['all','react'],
    "img": "8",
    "title": "ife-course-demo",
    "subtitle": "react",
    "meta": "百度前端技术学院demo演示SPA ",
    "description": "百度前端技术学院demo演示SPA ",
    "demoUrl": "http://ife.giscafer.com",
    "gitUrl": "https://github.com/giscafer/ife-course-demo",
  },{
    "type": ['all','angular'],
    "img": "9",
    "title": "ng2-ife-course",
    "subtitle": "angular2",
    "meta": "百度前端技术学院demo演示SPA ",
    "description": "百度前端技术学院demo演示SPA ",
    "demoUrl": "http://ng2ife.giscafer.com",
    "gitUrl": "https://github.com/giscafer/ng2-ife-course",
  },{
    "type": ['all','nodejs'],
    "img": "10",
    "title": "moviesite",
    "subtitle": "Node.js • Jade • MongoDB",
    "meta": "学习nodejs时，开发的一个电影网站demo，功能包括注册登录，网站爬虫添加，电影查询删除等",
    "description": "学习nodejs时，开发的一个电影网站demo，功能包括注册登录，爬虫添加电影，电影查询删除等",
    "demoUrl": "http://ng2ife.giscafer.com",
    "gitUrl": "https://github.com/giscafer/ng2-ife-course",
  },{
    "type": ['all','other','wechat','java'],
    "img": "10",
    "title": "gisrobot",
    "subtitle": "Java • 微信公众号",
    "meta": " 微信公众号JAVA开发学习demo，天气预报查询、消息自动回复、中英文翻译",
    "description": "微信公众号开发机器人，天气预报查询、消息自动回复、中英文翻译",
    "demoUrl": "http://ng2ife.giscafer.com",
    "gitUrl": "https://github.com/giscafer/ng2-ife-course",
  },
];
